### ISSUE TITLE
Having problem that client not sending messages

### ISSUE THREAD

**Issue by Alex0007** [cgeorg/cycle-socket.io#10] opened 2016-09-07 23:27 UTC
Can you look at this and tell me, what is the problem here, why i don't get messages back from client?

https://github.com/Alex0007/cycle-socket.io-problem

**Comment by cgeorg** [comment] 2016-09-09 23:14
Hi Alex,

I took a look and I'm not sure what the problem is - it looks the the function in the driver that maps the events to the publish command isn't getting hit. I haven't used xstream, I just merged the pulll request - can you look at the code in that area to see what the problem might be?

**Comment by Alex0007** [comment] 2016-09-14 00:45
Can you publish xs working version? I can't use just github link as dependency because of npm prepublish task

**Comment by cgeorg** [comment] 2016-09-15 22:47
Published the fix as v3.0.1 to npm

**Closed as completed by cgeorg** 2016-09-15 22:47 UTC
